version: "3"
services:
  gatling:
    build: ./docker
    stdin_open: true
    tty: true
    volumes:
      - ./scenario/:/workdir/gatling-charts-highcharts-bundle-3.3.1/user-files
      - data:/workdir/gatling-charts-highcharts-bundle-3.3.1/results
    command: /bin/sh

  nginx:
    image: nginx:latest
    links:
      - gatling
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - data:/var/html

volumes:
  data:
    external: true
